name: solver-ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Run tests
        run: |
          python tests/run_tests.py
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: solver-report
          path: tests/report.json
